import { useEffect, useState } from 'react';
import { Outbreak, VaxRecord, Resident } from '../types';
import { v4 as uuidv4 } from 'uuid';

interface OutbreakVaccineMapping {
  [key: string]: string[];
}

export const OUTBREAK_VACCINE_MAP: OutbreakVaccineMapping = {
  'Influenza A': ['Influenza'],
  'Influenza B': ['Influenza'],
  'COVID-19': ['COVID-19'],
  'RSV': ['RSV'],
  'Norovirus': [],
  'C. difficile': [],
  'MRSA': [],
  'VRE': []
};

export const useOutbreakMonitor = (
  outbreaks: Outbreak[],
  vaxRecords: VaxRecord[],
  residents: Record<string, Resident>,
  onGenerateOffers: (offers: VaxRecord[]) => void
) => {
  const [processedOutbreaks, setProcessedOutbreaks] = useState<Set<string>>(new Set());

  useEffect(() => {
    const activeOutbreaks = outbreaks.filter(
      o => o.status === 'active' && !processedOutbreaks.has(o.id)
    );

    if (activeOutbreaks.length === 0) return;

    const newOffers: VaxRecord[] = [];

    activeOutbreaks.forEach(outbreak => {
      const vaccineTypes = OUTBREAK_VACCINE_MAP[outbreak.type] || [];
      if (vaccineTypes.length === 0) return;

      const activeResidents = Object.values(residents).filter(r => r.active_on_census);

      vaccineTypes.forEach(vaccineType => {
        activeResidents.forEach(resident => {
          const hasRecentVaccine = vaxRecords.some(v => 
            v.mrn === resident.mrn &&
            v.vaccine === vaccineType &&
            (v.status === 'given' || v.status === 'scheduled' || v.status === 'due')
          );

          if (!hasRecentVaccine) {
            newOffers.push({
              id: uuidv4(),
              residentId: resident.id,
              mrn: resident.mrn,
              residentName: resident.name,
              unit: resident.unit,
              room: resident.room,
              vaccine: vaccineType,
              vaccine_type: vaccineType,
              status: 'due',
              dateOffered: new Date().toISOString().split('T')[0],
              notes: `Auto-generated due to ${outbreak.type} outbreak`,
              outbreakId: outbreak.id,
              outbreakType: outbreak.type,
              autoGenerated: true,
              createdAt: new Date().toISOString()
            } as any);
          }
        });
      });

      setProcessedOutbreaks(prev => new Set([...prev, outbreak.id]));
    });

    if (newOffers.length > 0) {
      onGenerateOffers(newOffers);
    }
  }, [outbreaks, vaxRecords, residents, processedOutbreaks, onGenerateOffers]);

  return { processedOutbreaks };
};
